export enum MEGAVERSE {
    SPACE = "SPACE",
    POLYANET = "POLYANET",
    BLUE_SOLOON = "BLUE_SOLOON",
    RED_SOLOON = "RED_SOLOON",
    PURPLE_SOLOON = "PURPLE_SOLOON",
    WHITE_SOLOON = "WHITE_SOLOON",
    UP_COMETH = "UP_COMETH",
    RIGHT_COMETH = "RIGHT_COMETH",
    DOWN_COMETH = "DOWN_COMETH",
    LEFT_COMETH = "LEFT_COMETH",
}

export type MapResponse = string[][]
